package com.example;

import io.github.fludakit.jdbc.JdbcClient;
import org.jboss.weld.environment.se.Weld;
import org.jboss.weld.environment.se.WeldContainer;

import java.util.List;
import javax.sql.DataSource;

public class Main {

    public static void main(String[] args) throws Exception {
        try (WeldContainer container = new Weld().initialize()) {
            DataSource dataSource = container.select(DataSource.class).get();
            try (var conn = dataSource.getConnection(); var stmt = conn.createStatement()) {
                stmt.execute("CREATE TABLE engineers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255))");
            }

            EngineerService service = container.select(EngineerService.class).get();

            long adaId = service.create("Ada");
            service.create("Grace");

            List<Engineer> all = service.findAll();
            System.out.println("all = " + all);

            Engineer ada = service.findById(adaId);
            System.out.println("byId = " + ada);

            service.update(adaId, "Ada Lovelace");

            service.delete(adaId);

            JdbcClient client = container.select(JdbcClient.class).get();
            System.out.println("remaining = "
                    + client.sql("SELECT id, name FROM engineers ORDER BY id").query(Engineer.class).list());
        }
    }
}
